[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "platform"
version = "0.0.1"
authors = [
  { name="Patrik Keller", email="patrik.keller@konstanz.de" }
]
description = ""
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3"
]
dynamic = ["dependencies"]

[project.urls]
Homepage = "https://github.com/sgc-kn/sgc-dagster"
Issues = "https://github.com/sgc-kn/sgc-dagster/issues"

[tool.dagster]
module_name = "utils.dagster.definitions"
code_location_name = "sgc-platform"

[tool.setuptools.packages.find]
include = [ "integrations.*", "utils*" ]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
